2025-07-05 16:36:21,440 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Sat, 05 Jul 2025 16:36:21 +0000. Up 7.04 seconds.
2025-07-05 16:36:21,440 - main.py[DEBUG]: No kernel command line url found.
2025-07-05 16:36:21,440 - main.py[DEBUG]: Closing stdin.
2025-07-05 16:36:21,440 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-07-05 16:36:21,441 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-07-05 16:36:21,445 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-07-05 16:36:21,446 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-07-05 16:36:21,448 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-07-05 16:36:21,449 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-07-05 16:36:21,452 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-07-05 16:36:21,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-07-05 16:36:21,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-07-05 16:36:21,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-07-05 16:36:21,462 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-07-05 16:36:21,463 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-07-05 16:36:21,471 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-07-05 16:36:21,472 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-07-05 16:36:21,481 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-07-05 16:36:21,482 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-07-05 16:36:21,491 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-07-05 16:36:21,492 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-07-05 16:36:21,502 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-07-05 16:36:21,502 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-07-05 16:36:21,503 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-07-05 16:36:21,503 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-07-05 16:36:21,504 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-07-05 16:36:21,505 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-07-05 16:36:21,505 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-07-05 16:36:21,506 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-07-05 16:36:21,506 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-07-05 16:36:21,507 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-07-05 16:36:21,507 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-07-05 16:36:21,508 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:21,512 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:21,516 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-07-05 16:36:21,521 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-07-05 16:36:21,521 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-07-05 16:36:21,521 - stages.py[DEBUG]: no cache found
2025-07-05 16:36:21,521 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-07-05 16:36:21,521 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-07-05 16:36:21,526 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-07-05 16:36:21,527 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-07-05 16:36:21,539 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-07-05 16:36:21,539 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-07-05 16:36:21,539 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-07-05 16:36:21,539 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-07-05 16:36:21,539 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-07-05 16:36:21,539 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-07-05 16:36:21,540 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-07-05 16:36:21,540 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-07-05 16:36:21,540 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-07-05 16:36:21,540 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-07-05 16:36:21,540 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-07-05 16:36:21,540 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-07-05 16:36:21,540 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-07-05 16:36:21,540 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-07-05 16:36:21,540 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-07-05 16:36:21,541 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-07-05 16:36:21,548 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-07-05 16:36:21,548 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-07-05 16:36:21,549 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,563 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-07-05 16:36:21,565 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-07-05 16:36:21,566 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,568 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2472b) after 1 attempts
2025-07-05 16:36:21,569 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,571 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2025-07-05 16:36:21,571 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,573 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-07-05 16:36:21,573 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,575 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-07-05 16:36:21,575 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,577 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-07-05 16:36:21,577 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,579 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-07-05 16:36:21,579 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,581 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-07-05 16:36:21,581 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,583 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-07-05 16:36:21,583 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,584 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-07-05 16:36:21,585 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,586 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-07-05 16:36:21,586 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,588 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2025-07-05 16:36:21,588 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,590 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-07-05 16:36:21,590 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,592 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-07-05 16:36:21,592 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,594 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-07-05 16:36:21,594 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,596 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-07-05 16:36:21,596 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,597 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-07-05 16:36:21,598 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,599 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-07-05 16:36:21,600 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,601 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-07-05 16:36:21,602 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,604 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-07-05 16:36:21,604 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,606 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ (200, 230b) after 1 attempts
2025-07-05 16:36:21,606 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,609 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/ (200, 12b) after 1 attempts
2025-07-05 16:36:21,609 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/35.91.131.51' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/35.91.131.51', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,611 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/ipv4-associations/35.91.131.51 (200, 12b) after 1 attempts
2025-07-05 16:36:21,611 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,613 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/device-number (200, 1b) after 1 attempts
2025-07-05 16:36:21,613 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,615 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/interface-id (200, 21b) after 1 attempts
2025-07-05 16:36:21,615 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,617 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-hostname (200, 42b) after 1 attempts
2025-07-05 16:36:21,617 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,619 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/local-ipv4s (200, 12b) after 1 attempts
2025-07-05 16:36:21,619 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,621 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/mac (200, 17b) after 1 attempts
2025-07-05 16:36:21,621 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,623 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/owner-id (200, 12b) after 1 attempts
2025-07-05 16:36:21,624 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,625 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-hostname (200, 48b) after 1 attempts
2025-07-05 16:36:21,626 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,627 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/public-ipv4s (200, 12b) after 1 attempts
2025-07-05 16:36:21,627 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,632 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-group-ids (200, 20b) after 1 attempts
2025-07-05 16:36:21,632 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,634 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/security-groups (200, 56b) after 1 attempts
2025-07-05 16:36:21,635 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,636 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-id (200, 24b) after 1 attempts
2025-07-05 16:36:21,636 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,638 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2025-07-05 16:36:21,638 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,640 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-id (200, 21b) after 1 attempts
2025-07-05 16:36:21,640 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,642 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-07-05 16:36:21,642 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,644 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:54:c6:95:e9:95/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-07-05 16:36:21,644 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,647 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-07-05 16:36:21,647 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,649 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-07-05 16:36:21,649 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,650 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-07-05 16:36:21,651 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,652 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-07-05 16:36:21,653 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,654 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-07-05 16:36:21,655 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,656 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-07-05 16:36:21,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,658 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-07-05 16:36:21,658 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,661 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-07-05 16:36:21,661 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,663 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-07-05 16:36:21,663 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,665 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-07-05 16:36:21,665 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,667 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 42b) after 1 attempts
2025-07-05 16:36:21,667 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,669 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-07-05 16:36:21,669 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,671 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-07-05 16:36:21,671 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,673 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-07-05 16:36:21,673 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,675 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-07-05 16:36:21,675 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,677 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 42b) after 1 attempts
2025-07-05 16:36:21,677 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,679 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2025-07-05 16:36:21,679 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,681 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-07-05 16:36:21,681 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-07-05 16:36:21,683 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,685 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 48b) after 1 attempts
2025-07-05 16:36:21,685 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,687 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 12b) after 1 attempts
2025-07-05 16:36:21,687 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,688 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-07-05 16:36:21,689 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,690 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2025-07-05 16:36:21,690 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,692 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-07-05 16:36:21,692 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,694 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 476b) after 1 attempts
2025-07-05 16:36:21,694 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,696 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2025-07-05 16:36:21,696 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,697 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2025-07-05 16:36:21,698 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-07-05 16:36:21,700 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-07-05 16:36:21,700 - util.py[DEBUG]: Crawl of metadata service took 0.160 seconds
2025-07-05 16:36:21,702 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-07-05 16:36:21,702 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-07-05 16:36:21,703 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-07-05 16:36:21,704 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-07-05 16:36:21,704 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp0375g7s1) - w: [600] 12022 bytes/chars
2025-07-05 16:36:21,705 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpryymzmja) - w: [644] 7880 bytes/chars
2025-07-05 16:36:21,705 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-07-05 16:36:21,705 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-07-05 16:36:21,705 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-05 16:36:21,705 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-07-05 16:36:21,705 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,712 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-07-05 16:36:21,712 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-07-05 16:36:21,712 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,713 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-07-05 16:36:21,713 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-07-05 16:36:21,713 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,714 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-05 16:36:21,714 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-05 16:36:21,715 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,717 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-07-05 16:36:21,717 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-07-05 16:36:21,717 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,719 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-05 16:36:21,719 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,719 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-05 16:36:21,719 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-07-05 16:36:21,719 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-073ea975a5f7b892e'
2025-07-05 16:36:21,720 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e (recursive=True)
2025-07-05 16:36:21,723 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/handlers (recursive=False)
2025-07-05 16:36:21,724 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e (recursive=True)
2025-07-05 16:36:21,727 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/scripts (recursive=False)
2025-07-05 16:36:21,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e (recursive=True)
2025-07-05 16:36:21,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem (recursive=False)
2025-07-05 16:36:21,733 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-073ea975a5f7b892e/datasource (quiet=False)
2025-07-05 16:36:21,733 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/datasource - wb: [644] 29 bytes
2025-07-05 16:36:21,733 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/datasource (recursive=False)
2025-07-05 16:36:21,734 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/datasource (recursive=False)
2025-07-05 16:36:21,734 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-07-05 16:36:21,735 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-07-05 16:36:21,735 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-07-05 16:36:21,736 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-07-05 16:36:21,736 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-07-05 16:36:21,736 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-07-05 16:36:21,736 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-07-05 16:36:21,737 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-07-05 16:36:21,737 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-07-05 16:36:21,737 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-07-05 16:36:21,738 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-07-05 16:36:21,738 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-07-05 16:36:21,738 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-07-05 16:36:21,739 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-07-05 16:36:21,740 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12601 bytes
2025-07-05 16:36:21,740 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/obj.pkl (recursive=False)
2025-07-05 16:36:21,741 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/obj.pkl (recursive=False)
2025-07-05 16:36:21,741 - main.py[DEBUG]: [net] init will now be targeting instance id: i-073ea975a5f7b892e. new=True
2025-07-05 16:36:21,741 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-05 16:36:21,741 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-07-05 16:36:21,741 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,748 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-07-05 16:36:21,748 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-07-05 16:36:21,748 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,749 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-07-05 16:36:21,749 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-07-05 16:36:21,749 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,750 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-05 16:36:21,750 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-05 16:36:21,750 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,753 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-07-05 16:36:21,753 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-07-05 16:36:21,753 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,754 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-05 16:36:21,754 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,755 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-05 16:36:21,755 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-05 16:36:21,755 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-07-05 16:36:21,756 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-07-05 16:36:21,756 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-07-05 16:36:21,757 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-07-05 16:36:21,757 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-07-05 16:36:21,757 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-07-05 16:36:21,757 - stages.py[DEBUG]: network config disabled by system_cfg
2025-07-05 16:36:21,757 - stages.py[INFO]: network config is disabled by system_cfg
2025-07-05 16:36:21,757 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-07-05 16:36:21,757 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-07-05 16:36:21,757 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt - wb: [600] 2472 bytes
2025-07-05 16:36:21,758 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt (recursive=False)
2025-07-05 16:36:21,759 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt (recursive=False)
2025-07-05 16:36:21,760 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,763 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt.i - wb: [600] 2494 bytes
2025-07-05 16:36:21,763 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt.i (recursive=False)
2025-07-05 16:36:21,764 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/user-data.txt.i (recursive=False)
2025-07-05 16:36:21,765 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt - wb: [600] 0 bytes
2025-07-05 16:36:21,765 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt (recursive=False)
2025-07-05 16:36:21,766 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt (recursive=False)
2025-07-05 16:36:21,767 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt.i - wb: [600] 308 bytes
2025-07-05 16:36:21,767 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt.i (recursive=False)
2025-07-05 16:36:21,768 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data.txt.i (recursive=False)
2025-07-05 16:36:21,768 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt - wb: [600] 0 bytes
2025-07-05 16:36:21,768 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt (recursive=False)
2025-07-05 16:36:21,769 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt (recursive=False)
2025-07-05 16:36:21,770 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt.i - wb: [600] 308 bytes
2025-07-05 16:36:21,770 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt.i (recursive=False)
2025-07-05 16:36:21,771 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/vendor-data2.txt.i (recursive=False)
2025-07-05 16:36:21,772 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-07-05 16:36:21,772 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-20-73.us-west-2.compute.internal (ip-172-31-20-73)
2025-07-05 16:36:21,773 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-20-73.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:21,870 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-20-73.us-west-2.compute.internal
2025-07-05 16:36:21,870 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-20-73.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:21,875 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpw08b3wl4) - w: [644] 90 bytes/chars
2025-07-05 16:36:21,875 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/consume_data - wb: [644] 25 bytes
2025-07-05 16:36:21,876 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/consume_data (recursive=False)
2025-07-05 16:36:21,877 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/consume_data (recursive=False)
2025-07-05 16:36:21,878 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/consume_data'>)
2025-07-05 16:36:21,878 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-07-05 16:36:21,878 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-07-05 16:36:21,879 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,879 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,880 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-07-05 16:36:21,880 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2025-07-05 16:36:21,880 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2025-07-05 16:36:21,880 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,881 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-07-05 16:36:21,881 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2025-07-05 16:36:21,881 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2025-07-05 16:36:21,881 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1823 bytes
2025-07-05 16:36:21,882 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/scripts/user-data.txt (recursive=False)
2025-07-05 16:36:21,883 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/scripts/user-data.txt (recursive=False)
2025-07-05 16:36:21,883 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-07-05 16:36:21,884 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/cloud-config.txt - wb: [600] 154 bytes
2025-07-05 16:36:21,884 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/cloud-config.txt (recursive=False)
2025-07-05 16:36:21,885 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/cloud-config.txt (recursive=False)
2025-07-05 16:36:21,885 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,886 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,886 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,886 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,886 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-07-05 16:36:21,886 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-07-05 16:36:21,886 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-07-05 16:36:21,886 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-07-05 16:36:21,886 - stages.py[DEBUG]: no vendordata from datasource
2025-07-05 16:36:21,886 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-07-05 16:36:21,886 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-07-05 16:36:21,886 - stages.py[DEBUG]: no vendordata2 from datasource
2025-07-05 16:36:21,886 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-07-05 16:36:21,886 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-07-05 16:36:21,886 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-07-05 16:36:21,886 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,893 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-07-05 16:36:21,893 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-07-05 16:36:21,893 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,894 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-07-05 16:36:21,894 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-07-05 16:36:21,894 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,896 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-07-05 16:36:21,896 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-07-05 16:36:21,896 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,898 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-07-05 16:36:21,898 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-07-05 16:36:21,899 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,900 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-07-05 16:36:21,900 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,900 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-07-05 16:36:21,900 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-07-05 16:36:21,900 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-07-05 16:36:21,900 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,901 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,902 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,957 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-07-05 16:36:21,957 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-07-05 16:36:21,957 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-07-05 16:36:21,960 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-07-05 16:36:21,960 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16772 bytes
2025-07-05 16:36:21,962 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/obj.pkl (recursive=False)
2025-07-05 16:36:21,963 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/obj.pkl (recursive=False)
2025-07-05 16:36:21,963 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-07-05 16:36:21,963 - main.py[DEBUG]: no di_report found in config.
2025-07-05 16:36:21,965 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,965 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,967 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,968 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,970 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,970 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,972 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,972 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,974 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,975 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,978 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,978 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,980 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,980 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,985 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,985 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,987 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,987 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,990 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,990 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,992 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,992 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,994 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,994 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,996 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,996 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:21,999 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:21,999 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,001 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,002 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,004 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,004 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,006 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-07-05 16:36:22,006 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-07-05 16:36:22,007 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-07-05 16:36:22,007 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85ca970>)
2025-07-05 16:36:22,007 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-07-05 16:36:22,007 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-07-05 16:36:22,007 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-07-05 16:36:22,007 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-07-05 16:36:22,007 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_seed_random - wb: [644] 25 bytes
2025-07-05 16:36:22,008 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_seed_random (recursive=False)
2025-07-05 16:36:22,009 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_seed_random (recursive=False)
2025-07-05 16:36:22,009 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_seed_random'>)
2025-07-05 16:36:22,009 - cc_seed_random.py[DEBUG]: no command provided
2025-07-05 16:36:22,009 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-07-05 16:36:22,009 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-07-05 16:36:22,009 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-07-05 16:36:22,009 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85ca970>)
2025-07-05 16:36:22,010 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-07-05 16:36:22,010 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-07-05 16:36:22,010 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-07-05 16:36:22,010 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-07-05 16:36:22,010 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_files - wb: [644] 25 bytes
2025-07-05 16:36:22,010 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_files (recursive=False)
2025-07-05 16:36:22,011 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_files (recursive=False)
2025-07-05 16:36:22,012 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_files'>)
2025-07-05 16:36:22,012 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-07-05 16:36:22,012 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-07-05 16:36:22,012 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-07-05 16:36:22,012 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-07-05 16:36:22,012 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_metadata - wb: [644] 25 bytes
2025-07-05 16:36:22,012 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_metadata (recursive=False)
2025-07-05 16:36:22,013 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_metadata (recursive=False)
2025-07-05 16:36:22,014 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_write_metadata'>)
2025-07-05 16:36:22,014 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-07-05 16:36:22,016 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-07-05 16:36:22,016 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-07-05 16:36:22,017 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-07-05 16:36:22,017 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-07-05 16:36:22,017 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-07-05 16:36:22,018 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-07-05 16:36:22,018 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-07-05 16:36:22,018 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-07-05 16:36:22,018 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-07-05 16:36:22,019 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-07-05 16:36:22,019 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85cab80>)
2025-07-05 16:36:22,019 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-07-05 16:36:22,019 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,027 - util.py[DEBUG]: Reading from /proc/1457/mountinfo (quiet=False)
2025-07-05 16:36:22,027 - util.py[DEBUG]: Read 2927 bytes from /proc/1457/mountinfo
2025-07-05 16:36:22,028 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-07-05 16:36:22,028 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-07-05 16:36:22,028 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-07-05 16:36:22,028 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-07-05 16:36:22,028 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,075 - util.py[DEBUG]: resize_devices took 0.048 seconds
2025-07-05 16:36:22,076 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-07-05 16:36:22,076 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-07-05 16:36:22,076 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-07-05 16:36:22,076 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-07-05 16:36:22,076 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85ca970>)
2025-07-05 16:36:22,076 - util.py[DEBUG]: Reading from /proc/1457/mountinfo (quiet=False)
2025-07-05 16:36:22,076 - util.py[DEBUG]: Read 2927 bytes from /proc/1457/mountinfo
2025-07-05 16:36:22,077 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-07-05 16:36:22,077 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-07-05 16:36:22,078 - util.py[DEBUG]: Forked child 1571 who will run callback log_time
2025-07-05 16:36:22,078 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-07-05 16:36:22,079 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,079 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-07-05 16:36:22,079 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-07-05 16:36:22,080 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-07-05 16:36:22,080 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_disk_setup - wb: [644] 23 bytes
2025-07-05 16:36:22,082 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_disk_setup (recursive=False)
2025-07-05 16:36:22,084 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_disk_setup (recursive=False)
2025-07-05 16:36:22,084 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_disk_setup'>)
2025-07-05 16:36:22,084 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-07-05 16:36:22,084 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-07-05 16:36:22,085 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-07-05 16:36:22,085 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_mounts - wb: [644] 24 bytes
2025-07-05 16:36:22,085 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_mounts (recursive=False)
2025-07-05 16:36:22,086 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_mounts (recursive=False)
2025-07-05 16:36:22,087 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_mounts'>)
2025-07-05 16:36:22,087 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-07-05 16:36:22,087 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-07-05 16:36:22,087 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-07-05 16:36:22,087 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-07-05 16:36:22,088 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-07-05 16:36:22,088 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: no need to setup swap
2025-07-05 16:36:22,088 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-07-05 16:36:22,088 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-07-05 16:36:22,088 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-07-05 16:36:22,088 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-07-05 16:36:22,088 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85cad60>)
2025-07-05 16:36:22,089 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-07-05 16:36:22,089 - util.py[DEBUG]: Read 90 bytes from /var/lib/cloud/data/set-hostname
2025-07-05 16:36:22,089 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-07-05 16:36:22,089 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-07-05 16:36:22,089 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-07-05 16:36:22,089 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-07-05 16:36:22,089 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85cab80>)
2025-07-05 16:36:22,090 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-20-73.us-west-2.compute.internal (ip-172-31-20-73)
2025-07-05 16:36:22,090 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,091 - util.py[DEBUG]: backgrounded Resizing took 0.012 seconds
2025-07-05 16:36:22,094 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-20-73.us-west-2.compute.internal in 1 files
2025-07-05 16:36:22,094 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 42 bytes
2025-07-05 16:36:22,095 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-07-05 16:36:22,096 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-07-05 16:36:22,096 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-07-05 16:36:22,096 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-07-05 16:36:22,097 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-07-05 16:36:22,097 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f09d85cad60>)
2025-07-05 16:36:22,097 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-07-05 16:36:22,097 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-07-05 16:36:22,097 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-07-05 16:36:22,097 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-07-05 16:36:22,097 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ca_certs - wb: [644] 25 bytes
2025-07-05 16:36:22,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ca_certs (recursive=False)
2025-07-05 16:36:22,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ca_certs (recursive=False)
2025-07-05 16:36:22,099 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ca_certs'>)
2025-07-05 16:36:22,099 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-07-05 16:36:22,099 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-07-05 16:36:22,099 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-07-05 16:36:22,099 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-07-05 16:36:22,099 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_rsyslog - wb: [644] 25 bytes
2025-07-05 16:36:22,100 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_rsyslog (recursive=False)
2025-07-05 16:36:22,101 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_rsyslog (recursive=False)
2025-07-05 16:36:22,101 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_rsyslog'>)
2025-07-05 16:36:22,101 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-07-05 16:36:22,101 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-07-05 16:36:22,101 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-07-05 16:36:22,101 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-07-05 16:36:22,101 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_selinux - wb: [644] 25 bytes
2025-07-05 16:36:22,102 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_selinux (recursive=False)
2025-07-05 16:36:22,103 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_selinux (recursive=False)
2025-07-05 16:36:22,103 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_selinux'>)
2025-07-05 16:36:22,109 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-07-05 16:36:22,109 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-07-05 16:36:22,110 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-07-05 16:36:22,110 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-07-05 16:36:22,110 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-07-05 16:36:22,110 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-07-05 16:36:22,110 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-07-05 16:36:22,110 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-07-05 16:36:22,110 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_users_groups - wb: [644] 25 bytes
2025-07-05 16:36:22,111 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_users_groups (recursive=False)
2025-07-05 16:36:22,112 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_users_groups (recursive=False)
2025-07-05 16:36:22,113 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_users_groups'>)
2025-07-05 16:36:22,113 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-07-05 16:36:22,114 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,150 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-07-05 16:36:22,151 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-07-05 16:36:22,152 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-07-05 16:36:22,153 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-07-05 16:36:22,154 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-07-05 16:36:22,155 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-07-05 16:36:22,155 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-07-05 16:36:22,155 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-07-05 16:36:22,155 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ssh - wb: [644] 25 bytes
2025-07-05 16:36:22,156 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ssh (recursive=False)
2025-07-05 16:36:22,157 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ssh (recursive=False)
2025-07-05 16:36:22,157 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ssh'>)
2025-07-05 16:36:22,158 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,172 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-07-05 16:36:22,178 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,186 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-07-05 16:36:22,192 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-07-05 16:36:22,192 - util.py[DEBUG]: Read 129 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-07-05 16:36:22,192 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-07-05 16:36:22,192 - util.py[DEBUG]: Read 209 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-07-05 16:36:22,192 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-07-05 16:36:22,193 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-07-05 16:36:22,194 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2025-07-05 16:36:22,194 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2025-07-05 16:36:22,195 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-05 16:36:22,195 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,195 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,195 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-07-05 16:36:22,196 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-07-05 16:36:22,196 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-07-05 16:36:22,196 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-05 16:36:22,196 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,196 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,196 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-07-05 16:36:22,197 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-07-05 16:36:22,197 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-07-05 16:36:22,198 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-07-05 16:36:22,199 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-05 16:36:22,199 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,199 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,199 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-07-05 16:36:22,200 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-07-05 16:36:22,200 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-07-05 16:36:22,200 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-07-05 16:36:22,200 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,200 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-07-05 16:36:22,200 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-07-05 16:36:22,201 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-07-05 16:36:22,201 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-07-05 16:36:22,202 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpx5dyzs5z) - w: [644] 484 bytes/chars
2025-07-05 16:36:22,202 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-05 16:36:22,202 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-07-05 16:36:22,202 - util.py[DEBUG]: cloud-init mode 'init' took 0.835 seconds (0.83)
2025-07-05 16:36:22,202 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-07-05 16:36:22,783 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Sat, 05 Jul 2025 16:36:22 +0000. Up 8.33 seconds.
2025-07-05 16:36:22,785 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,785 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,788 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,788 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,790 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,790 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,792 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,792 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,795 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,796 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,799 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,799 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,802 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,802 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,804 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,804 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,806 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,806 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,808 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:22,808 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:22,809 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-07-05 16:36:22,810 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-07-05 16:36:22,810 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-07-05 16:36:22,810 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-07-05 16:36:22,810 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_keyboard - wb: [644] 25 bytes
2025-07-05 16:36:22,812 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_keyboard (recursive=False)
2025-07-05 16:36:22,814 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_keyboard (recursive=False)
2025-07-05 16:36:22,815 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_keyboard'>)
2025-07-05 16:36:22,815 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-07-05 16:36:22,815 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-07-05 16:36:22,815 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-07-05 16:36:22,815 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-07-05 16:36:22,815 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_locale - wb: [644] 24 bytes
2025-07-05 16:36:22,816 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_locale (recursive=False)
2025-07-05 16:36:22,816 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_locale (recursive=False)
2025-07-05 16:36:22,817 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_locale'>)
2025-07-05 16:36:22,817 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-07-05 16:36:22,817 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-07-05 16:36:22,817 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-07-05 16:36:22,817 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-07-05 16:36:22,817 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-07-05 16:36:22,817 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2025-07-05 16:36:22,819 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-07-05 16:36:22,821 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-07-05 16:36:22,822 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-07-05 16:36:22,822 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-07-05 16:36:22,822 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-07-05 16:36:22,822 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_set_passwords - wb: [644] 25 bytes
2025-07-05 16:36:22,823 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_set_passwords (recursive=False)
2025-07-05 16:36:22,823 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_set_passwords (recursive=False)
2025-07-05 16:36:22,824 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_set_passwords'>)
2025-07-05 16:36:22,824 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-07-05 16:36:22,840 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-07-05 16:36:22,841 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-07-05 16:36:22,841 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-07-05 16:36:22,841 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-07-05 16:36:22,841 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-07-05 16:36:22,841 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-07-05 16:36:22,841 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-07-05 16:36:22,842 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_variables - wb: [644] 25 bytes
2025-07-05 16:36:22,843 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_variables (recursive=False)
2025-07-05 16:36:22,844 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_variables (recursive=False)
2025-07-05 16:36:22,844 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_variables'>)
2025-07-05 16:36:22,844 - cc_yum_variables.py[INFO]: handling yum-variables
2025-07-05 16:36:22,844 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.7, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-07-05 16:36:22,844 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-07-05 16:36:22,844 - cc_yum_variables.py[INFO]: No yum vars to set
2025-07-05 16:36:22,844 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-07-05 16:36:22,844 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-07-05 16:36:22,844 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-07-05 16:36:22,845 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_add_repo - wb: [644] 25 bytes
2025-07-05 16:36:22,845 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_add_repo (recursive=False)
2025-07-05 16:36:22,846 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_add_repo (recursive=False)
2025-07-05 16:36:22,846 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_yum_add_repo'>)
2025-07-05 16:36:22,846 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-07-05 16:36:22,846 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-07-05 16:36:22,846 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-07-05 16:36:22,846 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-07-05 16:36:22,847 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ntp - wb: [644] 25 bytes
2025-07-05 16:36:22,847 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ntp (recursive=False)
2025-07-05 16:36:22,848 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ntp (recursive=False)
2025-07-05 16:36:22,848 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_ntp'>)
2025-07-05 16:36:22,848 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-07-05 16:36:22,848 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-07-05 16:36:22,848 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-07-05 16:36:22,848 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-07-05 16:36:22,848 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_timezone - wb: [644] 25 bytes
2025-07-05 16:36:22,849 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_timezone (recursive=False)
2025-07-05 16:36:22,849 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_timezone (recursive=False)
2025-07-05 16:36:22,850 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_timezone'>)
2025-07-05 16:36:22,850 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-07-05 16:36:22,850 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-07-05 16:36:22,850 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-07-05 16:36:22,850 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-07-05 16:36:22,850 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f4a002c0220>)
2025-07-05 16:36:22,850 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-07-05 16:36:22,850 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-07-05 16:36:22,850 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-07-05 16:36:22,850 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-07-05 16:36:22,851 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_runcmd - wb: [644] 25 bytes
2025-07-05 16:36:22,851 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_runcmd (recursive=False)
2025-07-05 16:36:22,852 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_runcmd (recursive=False)
2025-07-05 16:36:22,852 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-073ea975a5f7b892e/sem/config_runcmd'>)
2025-07-05 16:36:22,852 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-07-05 16:36:22,852 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-07-05 16:36:22,852 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-07-05 16:36:22,853 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpnkdj19kj) - w: [644] 512 bytes/chars
2025-07-05 16:36:22,853 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-05 16:36:22,853 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-07-05 16:36:22,853 - util.py[DEBUG]: cloud-init mode 'modules' took 0.194 seconds (0.20)
2025-07-05 16:36:22,853 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-07-05 16:36:23,245 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Sat, 05 Jul 2025 16:36:23 +0000. Up 8.82 seconds.
2025-07-05 16:36:23,249 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-07-05 16:36:23,249 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-07-05 16:36:23,251 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-07-05 16:36:23,251 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2025-07-05 16:36:23,251 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2025-07-05 16:36:23,251 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7febad25ef70>)
2025-07-05 16:36:23,252 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2025-07-05 16:36:32,172 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-07-05 16:36:32,172 - main.py[DEBUG]: Ran 1 modules with 0 failures
2025-07-05 16:36:32,173 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpgwpqedeg) - w: [644] 540 bytes/chars
2025-07-05 16:36:32,173 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp7yucruvp) - w: [644] 64 bytes/chars
2025-07-05 16:36:32,173 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-07-05 16:36:32,173 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-07-05 16:36:32,173 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2025-07-05 16:36:32,173 - util.py[DEBUG]: cloud-init mode 'modules' took 8.995 seconds (7.61)
2025-07-05 16:36:32,173 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
